<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>AmandsGoofySounds</RootNamespace>
    <AssemblyName>AmandsGoofySounds</AssemblyName>
    <Version>2.4.0</Version>
    <AssemblyVersion>2.4.0.0</AssemblyVersion>
    <FileVersion>2.4.0.0</FileVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\References\Tarkov\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\References\Bepinex\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\References\Tarkov\Comfort.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>..\References\SPT\spt-reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\References\Tarkov\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\References\Tarkov\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\References\Tarkov\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>..\References\Tarkov\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\References\Tarkov\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
